services:
  app:
    container_name: app
    build:
      context: ..
    working_dir: /app
    restart: always
  nginx:
    container_name: nginx-static-server
    build:
      context: ..
    ports:
      - "80:80"
    restart: always