services:
  nginx:
    container_name: nginx-server
    build:
      context: ../.vendor
      dockerfile: Dockerfile
    volumes:
      - ../../output:/usr/vendor/output
      - ../../playground:/usr/vendor/playground
    ports:
      - "80:80"
    restart: always